services:
  netbird-dns-sync:
    image: "ghcr.io/ix64/netbird-dns-sync:main"
    restart: unless-stopped
    environment:
      NETBIRD_ENDPOINT: https://netbird.example.com
      NETBIRD_ACCESS_TOKEN: ...... # see https://docs.netbird.io/how-to/access-netbird-public-api#creating-an-access-token
      CLOUDFLARE_DOMAIN: example.com
      CLOUDFLARE_API_TOKEN: ...... # see https://dash.cloudflare.com/profile/api-tokens

